
package com.bivgroup.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContractFirstWebService", targetNamespace = "http://www.bivgroup.com/ContractFirstWebService", wsdlLocation = "file:/home/programmer/IdeaProjects/ContractFirstWebService/src/main/resources/my.wsdl")
public class ContractFirstWebService
    extends Service
{

    private final static URL CONTRACTFIRSTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTRACTFIRSTWEBSERVICE_EXCEPTION;
    private final static QName CONTRACTFIRSTWEBSERVICE_QNAME = new QName("http://www.bivgroup.com/ContractFirstWebService", "ContractFirstWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/programmer/IdeaProjects/ContractFirstWebService/src/main/resources/my.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTRACTFIRSTWEBSERVICE_WSDL_LOCATION = url;
        CONTRACTFIRSTWEBSERVICE_EXCEPTION = e;
    }

    public ContractFirstWebService() {
        super(__getWsdlLocation(), CONTRACTFIRSTWEBSERVICE_QNAME);
    }

    public ContractFirstWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTRACTFIRSTWEBSERVICE_QNAME, features);
    }

    public ContractFirstWebService(URL wsdlLocation) {
        super(wsdlLocation, CONTRACTFIRSTWEBSERVICE_QNAME);
    }

    public ContractFirstWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTRACTFIRSTWEBSERVICE_QNAME, features);
    }

    public ContractFirstWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContractFirstWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContractFirstWebServicePort
     */
    @WebEndpoint(name = "ContractFirstWebServicePort")
    public ContractFirstWebServicePort getContractFirstWebServicePort() {
        return super.getPort(new QName("http://www.bivgroup.com/ContractFirstWebService", "ContractFirstWebServicePort"), ContractFirstWebServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContractFirstWebServicePort
     */
    @WebEndpoint(name = "ContractFirstWebServicePort")
    public ContractFirstWebServicePort getContractFirstWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bivgroup.com/ContractFirstWebService", "ContractFirstWebServicePort"), ContractFirstWebServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTRACTFIRSTWEBSERVICE_EXCEPTION!= null) {
            throw CONTRACTFIRSTWEBSERVICE_EXCEPTION;
        }
        return CONTRACTFIRSTWEBSERVICE_WSDL_LOCATION;
    }

}
