
package com.bivgroup.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContractFirstWebServicePort", targetNamespace = "http://www.bivgroup.com/ContractFirstWebService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ContractFirstWebServicePort {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnXMLString", partName = "returnXMLString")
    public String getXML();

}
